In [23]:
from AlignmentMeterLVA import *
%reload_ext autoreload
%autoreload 2

In [8]:
org_alignments_df = pickle.load(open('org_alignments_df.p', 'rb'))
leg_votes_df = pickle.load(open('leg_votes_df.p', 'rb'))

In [9]:
org_alignments_df.head()

,oid,bid,hid,analysis_flag,alignment,name,date
3,8,CA_201520160AB1056,366,0,For,California State Association Of Counties,2015-06-30
4,8,CA_201520160AB1159,130,0,For,California State Association Of Counties,2015-04-13
5,8,CA_201520160AB1193,184,0,Against,California State Association Of Counties,2015-04-28
6,8,CA_201520160AB1238,716,0,For,California State Association Of Counties,2016-01-21
7,8,CA_201520160AB1239,174,0,For,California State Association Of Counties,2015-04-27

In [10]:
leg_votes_df.head()

,pid,voteId,result,state,lastTouched,dr_id,bid,VoteDate,hid,first,middle,last
0,65,39065,For,CA,2016-07-12 23:31:00,235727,CA_201520160AB1,2015-06-10,305,Janet,None,Nguyen
1,92,39065,For,CA,2016-07-12 23:31:00,341579,CA_201520160AB1,2015-06-10,305,Jim,None,Beall
2,99,39065,For,CA,2016-07-12 23:31:00,362651,CA_201520160AB1,2015-06-10,305,Robert,None,Hertzberg
3,103,39065,For,CA,2016-07-12 23:31:00,372163,CA_201520160AB1,2015-06-10,305,Ed,None,Hernandez
4,104,39065,For,CA,2016-07-12 23:31:00,375538,CA_201520160AB1,2015-06-10,305,Fran,None,Pavley

In [31]:
org_alignments_df['date'].max()

datetime.date(2016, 8, 31)

In [35]:
for ((oid, bid), oid_alignments_df) in org_alignments_df.groupby(['oid', 'bid']):
    #print(oid_alignments_df)
    min_date = oid_alignments_df['date'].min()
    # Still technically a dataframe to be used in the join
    alignment_row = oid_alignments_df[oid_alignments_df['date'] == min_date]
    alignment = alignment_row['alignment'].iloc[0]
    alignment_votes_df = leg_votes_df.merge(alignment_row, on=['bid'], suffixes=['_leg', '_org'])
    print(alignment_votes_df.head())
    print(type(alignment_votes_df['VoteDate'].iloc[0]))
    print(type(alignment_votes_df['date'].iloc[0]))
    idx = pd.to_datetime(alignment_votes_df['date']) <= pd.to_datetime(alignment_votes_df['VoteDate'])
    print(idx)
    alignment_votes_df = alignment_votes_df[idx]
    print(min_date)
    print(alignment_votes_df)
    break

   pid  voteId   result state         lastTouched   dr_id                 bid  \
0    6   37342      For    CA 2016-07-12 23:26:52   19847  CA_201520160AB1056
1    7   37342      For    CA 2016-07-12 23:26:52   23573  CA_201520160AB1056
2   31   37342  Against    CA 2016-07-12 23:26:52  112172  CA_201520160AB1056
3   35   37342      For    CA 2016-07-12 23:26:52  124734  CA_201520160AB1056
4   89   37342      For    CA 2016-07-12 23:26:52  332333  CA_201520160AB1056

    VoteDate  hid_leg   first middle       last  oid  hid_org  analysis_flag  \
0 2015-04-29      190  Autumn   None      Burke    8      366              0
1 2015-04-29      190   David   None       Chiu    8      366              0
2 2015-04-29      190   Kevin   None     Mullin    8      366              0
3 2015-04-29      190    Marc   None  Steinorth    8      366              0
4 2015-04-29      190   Patty   None      Lopez    8      366              0

  alignment                                      name        date
0       For  California State Association Of Counties  2015-06-30
1       For  California State Association Of Counties  2015-06-30
2       For  California State Association Of Counties  2015-06-30
3       For  California State Association Of Counties  2015-06-30
4       For  California State Association Of Counties  2015-06-30
<class 'pandas.tslib.Timestamp'>
<class 'datetime.date'>
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24     True
25     True
26     True
27     True
28     True
29     True
30     True
31     True
32     True
33     True
34     True
35     True
36     True
37     True
dtype: bool
2015-06-30
      pid  voteId   result state         lastTouched   dr_id  \
24     25   41142      For    CA 2016-07-12 23:31:40   92234
25     26   41142  Against    CA 2016-07-12 23:31:40   95865
26     57   41142      For    CA 2016-07-12 23:31:40  207645
27     60   41142      For    CA 2016-07-12 23:31:40  219207
28     63   41142      For    CA 2016-07-12 23:31:40  230064
29     98   41142      For    CA 2016-07-12 23:31:40  359880
30  10481   41142      For    CA 2016-07-12 23:31:40  447424
31     52   42729      For    CA 2016-07-12 23:33:57  190212
32     58   42729      For    CA 2016-07-12 23:33:57  212258
33     62   42729      For    CA 2016-07-12 23:33:57  226914
34     66   42729      For    CA 2016-07-12 23:33:57  240810
35     68   42729      For    CA 2016-07-12 23:33:57  248922
36     92   42729      For    CA 2016-07-12 23:33:57  342997
37    107   42729      For    CA 2016-07-12 23:33:57  386516

                   bid   VoteDate  hid_leg    first middle      last  oid  \
24  CA_201520160AB1056 2015-06-30      366     Bill   None   Monning    8
25  CA_201520160AB1056 2015-06-30      366     Jeff   None     Stone    8
26  CA_201520160AB1056 2015-06-30      366     Joel   None  Anderson    8
27  CA_201520160AB1056 2015-06-30      366     Mark   None      Leno    8
28  CA_201520160AB1056 2015-06-30      366    Carol   None       Liu    8
29  CA_201520160AB1056 2015-06-30      366     Loni   None   Hancock    8
30  CA_201520160AB1056 2015-06-30      366    Steve   None    Glazer    8
31  CA_201520160AB1056 2015-08-27      524     Tony   None   Mendoza    8
32  CA_201520160AB1056 2015-08-27      524      Pat   None     Bates    8
33  CA_201520160AB1056 2015-08-27      524   Connie   None     Leyva    8
34  CA_201520160AB1056 2015-08-27      524    Jerry   None      Hill    8
35  CA_201520160AB1056 2015-08-27      524      Jim   None   Nielsen    8
36  CA_201520160AB1056 2015-08-27      524      Jim   None     Beall    8
37  CA_201520160AB1056 2015-08-27      524  Ricardo   None      Lara    8

    hid_org  analysis_flag alignment  \
24      366              0       For
25      366              0       For
26      366              0       For
27      366              0       For
28      366              0       For
29      366              0       For
30      366              0       For
31      366              0       For
32      366              0       For
33      366              0       For
34      366              0       For
35      366              0       For
36      366              0       For
37      366              0       For

                                        name        date
24  California State Association Of Counties  2015-06-30
25  California State Association Of Counties  2015-06-30
26  California State Association Of Counties  2015-06-30
27  California State Association Of Counties  2015-06-30
28  California State Association Of Counties  2015-06-30
29  California State Association Of Counties  2015-06-30
30  California State Association Of Counties  2015-06-30
31  California State Association Of Counties  2015-06-30
32  California State Association Of Counties  2015-06-30
33  California State Association Of Counties  2015-06-30
34  California State Association Of Counties  2015-06-30
35  California State Association Of Counties  2015-06-30
36  California State Association Of Counties  2015-06-30
37  California State Association Of Counties  2015-06-30

In [67]:
def count_alignments(results, org_alignment):
    total_votes = 0
    aligned_votes = 0
    last_val = None
    for i, val in enumerate(results.values):
        #print(i+1)
        #Prevents similar votes after date to be counted more than once
        if val != last_val:
            last_val = val
            total_votes += 1
            if val == org_alignment:
                aligned_votes += 1

    return total_votes, aligned_votes

leg_scores = alignment_votes_df.groupby('pid')['result'].apply(count_alignments, alignment)
leg_scores_df = pd.DataFrame(leg_scores)
leg_scores_df.reset_index(level=0, inplace=True)
leg_scores_df['total_votes'] = leg_scores_df['result'].apply(lambda x: x[0])
leg_scores_df['aligned_votes'] = leg_scores_df['result'].apply(lambda x: x[1])
print(type(leg_scores_df['total_votes'].iloc[0]))
leg_scores_df

<class 'numpy.int64'>

      pid  result  total_votes  aligned_votes
0      25  (1, 1)            1              1
1      26  (1, 0)            1              0
2      52  (1, 1)            1              1
3      57  (1, 1)            1              1
4      58  (1, 1)            1              1
5      60  (1, 1)            1              1
6      62  (1, 1)            1              1
7      63  (1, 1)            1              1
8      66  (1, 1)            1              1
9      68  (1, 1)            1              1
10     92  (1, 1)            1              1
11     98  (1, 1)            1              1
12    107  (1, 1)            1              1
13  10481  (1, 1)            1              1

In [16]:
leg_votes_df.groupby(['pid', 'bid']).size()

pid    bid
1      CA_201520160AB1018    1
       CA_201520160AB1025    1
       CA_201520160AB1031    1
       CA_201520160AB1033    1
       CA_201520160AB1051    1
       CA_201520160AB1060    1
       CA_201520160AB1102    1
       CA_201520160AB1114    3
       CA_201520160AB1117    1
       CA_201520160AB1129    1
       CA_201520160AB1130    1
       CA_201520160AB1147    1
       CA_201520160AB1149    1
       CA_201520160AB1162    1
       CA_201520160AB1163    1
       CA_201520160AB1172    1
       CA_201520160AB1177    1
       CA_201520160AB1188    1
       CA_201520160AB1194    1
       CA_201520160AB12      1
       CA_201520160AB1211    1
       CA_201520160AB1218    1
       CA_201520160AB1223    1
       CA_201520160AB1231    1
       CA_201520160AB1234    1
       CA_201520160AB1235    1
       CA_201520160AB1261    1
       CA_201520160AB1278    1
       CA_201520160AB1282    1
       CA_201520160AB1291    1
                            ..
10481  CA_201520160SB888     1
       CA_201520160SB894     1
       CA_201520160SB905     1
       CA_201520160SB937     1
       CA_201520160SB941     1
       CA_201520160SB955     1
       CA_201520160SB966     1
17377  CA_201520160SB1059    1
       CA_201520160SB1060    1
       CA_201520160SB1155    1
       CA_201520160SB1180    1
       CA_201520160SB1226    1
       CA_201520160SB1227    1
       CA_201520160SB1232    1
       CA_201520160SB1260    1
       CA_201520160SB1263    1
       CA_201520160SB1336    1
       CA_201520160SB1339    1
       CA_201520160SB1427    1
       CA_201520160SB1455    1
       CA_201520160SB1466    1
       CA_201520160SB552     1
       CA_201520160SB820     1
       CA_201520160SB866     1
       CA_201520160SB906     1
       CA_201520160SB930     1
       CA_201520160SB942     1
       CA_201520160SB947     1
       CA_201520160SB980     1
       CA_201520160SB982     1
dtype: int64

In [52]:
count = 0
for ((oid, bid), oid_alignments_df) in org_alignments_df.groupby(['oid', 'bid']):
    if len(oid_alignments_df['alignment'].unique()) > 1:
        for ((date, alignment), oid_alignments_df) in oid_alignments_df.groupby(['date', 'alignment']):
            #if date == prev_date:
            #    alignment = no idea
            print(alignment)
            print(date)
        print('')
        if count == 3:
            break
        count+=1

Against
2016-06-21
For
2016-06-28

Against
2015-04-28
For
2015-04-28

For
2015-04-22
Against
2015-07-01

Against
2015-07-15
For
2015-09-10